import "../index.css";
import "../App.css";
import '../dist/styles/main.css'
import NavHeader from "@/app/components/nav-header";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
            <html lang="fr">
                <body>
                <NavHeader />
                <div className="page-layout">{children}</div>
                </body>
            </html>
    );
}
